services:
  db:
    image: docker.io/postgres:latest
    container_name: syllabus_scanner_db
    environment:
      POSTGRES_USER: oliver
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: syllabus_scanner_db
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: syllabus_scanner_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: syllabus_scanner_frontend
    command: npm run start
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - backend

